use_default_settings:
  engines:
    keep_only:
      - google
      - duckduckgo
      - bing
      - wikipedia
      - brave

general:
  instance_name: "Acronous SearXNG"
  debug: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "${SEARXNG_SECRET_KEY}"
  limiter: false
  image_proxy: false

ui:
  static_use_hash: true
  default_locale: "en"
  default_theme: "simple"

outgoing:
  request_timeout: 5.0
  max_request_timeout: 15.0
  useragent_suffix: ""
  pool_connections: 100
  pool_maxsize: 20
